fm_elfinder:
    instances:
        form:
            locale: '%app.default_locale%' # defaults to current request locale
            editor: form # other choices are tinymce or simple, and form
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            connector:
                debug: false # defaults to false
                roots: # at least one root must be defined
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: [ 'image/png', 'image/jpg', 'image/jpeg' ]
                        upload_deny: [ 'all' ]
                        upload_max_size: 2M